variables:
  GFX_VERSION_LINUX_DEFAULT: master_release/11110
  GFX_VERSION_LINUX_PVC: master_release/10703
  GFX_VERSION_LINUX_PUBLIC: VCSS_SG2_10270_u20.04_k5.10.54
  GFX_VERSION_WIN_DEFAULT: ci/master/11110
  GFX_VERSION_WIN_PUBLIC: ci/sdp/1011314
  DPCPP_VERSION_LINUX: sycl-nightly/20220418
  DPCPP_VERSION_WIN: sycl-nightly/165
